"""FeffCalculation — CalcJob wrapping a single FEFF execution."""

from __future__ import annotations

import json
import logging
from contextlib import contextmanager
from pathlib import Path

from aiida import orm
from aiida.common import CalcInfo, CodeInfo, datastructures
from aiida.engine import CalcJob, CalcJobProcessSpec

from aiida_feff.data.parameters import FeffParameters
from aiida_feff.data.pathcontributions import PathContributionsData
from aiida_feff.versions import dependency_versions

logger = logging.getLogger(__name__)

#: Packages whose version changes the generated feff.inp.
_GENERATOR_PACKAGES = ("aiida-feff", "pymatgen")

# Files written to / retrieved from the remote working directory
FEFF_INPUT_FILE = "feff.inp"
FEFF_LOG_FILE = "log.dat"
FEFF_XMUDA_FILE = "xmu.dat"
FEFF_CHI_FILE = "chi.dat"
FEFF_PATHS_FILE = "paths.dat"
FEFF_FILES_DAT = "files.dat"  # per-path amplitude ranking table
FEFF_AGGREGATE_SCRIPT = "_aggregate_paths.py"  # written to sandbox by prepare_for_submission
FEFF_AGGREGATE_CONFIG = "_feff_aggregate_config.json"  # threshold config for the above
FEFF_CONTRIBUTIONS_RAW = "contributions_raw.h5"  # produced by the aggregate script

# Files produced by the FEFF potentials step (CONTROL 1 1 1 0 0 0)
# that can be reused in subsequent runs (CONTROL 0 0 0 1 1 1).
# Derived from empirical testing — all are needed for module 6 (chi).
FEFF_POTENTIAL_FILES = (
    "pot.pad",
    "phase.pad",
    "xsect.json",
    "xsph.json",
    "genfmt.json",
    "ff2x.json",
    "geom.json",
    "atoms.json",
    "pot.json",
    "global.json",
    "path.json",
    "libpotph.json",
)

# Path to the bundled aggregation script (installed alongside this module)
_AGGREGATE_SCRIPT_PATH = Path(__file__).parent / FEFF_AGGREGATE_SCRIPT

# FEFF CONTROL cards, defined once and shared by the batch CalcJob and the
# ensemble workchain so the two paths cannot drift apart.
#: Run modules 1–3 only: compute potentials, write pot.pad / phase.pad, stop.
CONTROL_POT_ONLY = "1 1 1 0 0 0"
#: Run modules 4–6 only: reuse pre-computed potentials, skip SCF.
CONTROL_NO_POT = "0 0 0 1 1 1"

_N_CONTROL_MODULES = 6
_SPECTRUM_MODULES = slice(3, 6)


def is_potentials_only(control: str | None) -> bool:
    """True when a CONTROL card switches off the spectrum modules (4–6).

    Such a run is *expected* to finish without ``xmu.dat``, so the parser must
    not confuse it with a FEFF crash — which is what treating exit code 310 as
    acceptable used to do.
    """
    if not control:
        return False
    tokens = str(control).split()
    if len(tokens) != _N_CONTROL_MODULES:
        return False
    try:
        modules = [int(float(tok)) for tok in tokens]
    except ValueError:
        return False
    return all(m == 0 for m in modules[_SPECTRUM_MODULES])


def absorber_element(structure: orm.StructureData, absorbing_idx: int) -> str:
    """Return the element symbol of site *absorbing_idx* in *structure*.

    The symbol is written into the path-contributions metadata, so a wrong
    index must surface as an error rather than an empty string that later
    reads as "unknown absorber".
    """
    try:
        site = structure.sites[absorbing_idx]
    except IndexError as exc:
        raise ValueError(
            f"absorbing_atom index {absorbing_idx} is out of range for a "
            f"structure with {len(structure.sites)} sites."
        ) from exc
    return str(structure.get_kind(site.kind_name).symbols[0])


def as_lf_bytes(text: str) -> bytes:
    """Encode *text* as UTF-8 with LF line endings.

    Every file this plugin uploads is read by Fortran or a POSIX shell on the
    remote machine, so line endings are fixed here rather than inherited from
    whichever platform submitted the job.
    """
    return text.replace("\r\n", "\n").replace("\r", "\n").encode("utf-8")


def _generator_banner() -> str:
    """FEFF comment lines naming the code that generated this input.

    The card content comes from pymatgen's ``MPEXAFSSet.yaml``, which is
    unversioned inside pymatgen and can change every calculation's input on an
    upgrade.  Recording the version inside ``feff.inp`` puts it in the calcjob
    repository, where it survives with the input it explains — and makes AiiDA
    treat inputs built by different pymatgen versions as genuinely different,
    which for caching purposes they are.
    """
    versions = dependency_versions()
    named = ", ".join(
        f"{name} {versions[name]}" for name in _GENERATOR_PACKAGES if name in versions
    )
    return f"* Generated by {named}"


@contextmanager
def _spglib_new_error_handling():
    """Temporarily opt into spglib's new error handling.

    spglib 2.7 deprecates the path pymatgen's ``SpacegroupAnalyzer`` still
    triggers.  The flag is process-global, so it is restored on exit rather
    than left flipped for every other plugin sharing the daemon worker.
    """
    import spglib.error

    previous = spglib.error.OLD_ERROR_HANDLING
    spglib.error.OLD_ERROR_HANDLING = False
    try:
        yield
    finally:
        spglib.error.OLD_ERROR_HANDLING = previous


class FeffCalculation(CalcJob):
    r"""CalcJob that runs a single FEFF calculation.

    Inputs
    ------
    code : :class:`~aiida.orm.AbstractCode`
        The FEFF executable.
    python_code : :class:`~aiida.orm.AbstractCode`, optional
        Python 3 interpreter on the remote computer.  Required when
        ``path_cw_threshold >= 0``.  AiiDA runs ``_aggregate_paths.py`` as a
        second sequential command in the same job.  Register once per
        computer::

            verdi code create core.code.installed \\
                --computer=<c> --filepath-executable=$(which python3)
    structure : :class:`~aiida.orm.StructureData`
        Crystal / cluster structure.  The absorbing atom is identified by
        ``parameters.absorbing_atom`` (0-based site index).
    parameters : :class:`~aiida_feff.data.parameters.FeffParameters`
        Calculation control parameters.
    feff_input_file : :class:`~aiida.orm.SinglefileData`, optional
        If supplied, this pre-written ``feff.inp`` is used *as-is*,
        bypassing automatic generation from ``structure`` + ``parameters``.
        Useful for importing existing calculations.
    settings : :class:`~aiida.orm.Dict`, optional
        Low-level scheduler / plugin settings (see below).

    Outputs
    -------
    xas_data : :class:`~aiida_feff.data.xasdata.XasData`
        Parsed μ(E) and χ(k) spectra.
    retrieved : :class:`~aiida.orm.FolderData`
        All retrieved files.

    Exit codes
    ----------
    310  FEFF did not produce ``xmu.dat``.
    400  Unrecoverable parser error.

    Input combinations are rejected by the spec validator before a job is
    created, so there is no input-validation exit code: ``prepare_for_submission``
    cannot return one.  ``CalcJob.presubmit`` assigns to ``calc_info.uuid`` and
    :class:`~aiida.engine.ExitCode` is an immutable ``NamedTuple``, so returning
    an exit code there raises ``AttributeError`` inside the daemon instead of
    failing the job cleanly.
    """

    # ------------------------------------------------------------------
    # Defaults
    # ------------------------------------------------------------------
    _DEFAULT_RETRIEVE_LIST = [
        FEFF_LOG_FILE,
        FEFF_XMUDA_FILE,
        FEFF_CHI_FILE,
        FEFF_PATHS_FILE,
        FEFF_FILES_DAT,  # amplitude ranking; small file, kept for provenance
    ]
    _WITHMPI = False  # FEFF is serial by default; set via metadata

    # ------------------------------------------------------------------
    # define
    # ------------------------------------------------------------------

    @classmethod
    def define(cls, spec: CalcJobProcessSpec) -> None:  # type: ignore[override]
        """Define inputs, outputs and exit codes."""
        super().define(spec)

        # --- inputs -----------------------------------------------------------
        spec.input(
            "structure",
            valid_type=orm.StructureData,
            required=False,
            help="Cluster structure.  Required unless feff_input_file is provided.",
        )
        spec.input(
            "parameters",
            valid_type=FeffParameters,
            required=False,
            help="FEFF control parameters (edge, rpath, …).",
        )
        spec.input(
            "feff_input_file",
            valid_type=orm.SinglefileData,
            required=False,
            help="Pre-written feff.inp to use verbatim, bypassing auto-generation.",
        )
        spec.input(
            "remote_potentials",
            valid_type=orm.RemoteData,
            required=False,
            help=(
                "Remote working directory of a completed FEFF potentials-only run "
                "(e.g. CONTROL 1 1 1 0 0 0).  When supplied, pot.pad and phase.pad "
                "are copied from that directory into this job's working directory, "
                "so the SCF step can be skipped (use CONTROL 0 0 0 1 1 1 in parameters)."
            ),
        )
        spec.input(
            "settings",
            valid_type=orm.Dict,
            required=False,
            help=(
                "Miscellaneous plugin settings:\n"
                "  additional_retrieve_list : list[str]  — extra glob patterns\n"
                "  cmdline_params          : list[str]  — extra CLI flags\n"
            ),
        )
        spec.input(
            "python_code",
            valid_type=orm.AbstractCode,
            required=False,
            help=(
                "Python 3 interpreter on the remote computer.  Required when "
                "path_cw_threshold >= 0.  AiiDA runs '_aggregate_paths.py' as "
                "a second sequential command in the same job script."
            ),
        )
        spec.input(
            "path_cw_threshold",
            valid_type=orm.Float,
            default=lambda: orm.Float(-1.0),
            help=(
                "Minimum curved-wave amplitude ratio (0–100) for storing a "
                "scattering path.  FEFF's files.dat ranks all paths relative "
                "to the strongest path (= 100).  Set to e.g. 5.0 to keep only "
                "paths contributing at least 5% of the peak amplitude.  "
                "Set to 0 to store all paths.  "
                "Set to -1 (or any negative value) to skip path storage entirely.  "
                "Requires python_code when >= 0."
            ),
        )
        spec.input(
            "frame_idx",
            valid_type=orm.Int,
            default=lambda: orm.Int(0),
            help=(
                "Frame index of this calculation within an MD trajectory.  "
                "Written into the aggregation config and stored as metadata in "
                "the PathContributionsData HDF5.  Set automatically by "
                "EnsembleExafsWorkChain; leave at 0 for single-site runs."
            ),
        )
        spec.input(
            "site_idx",
            valid_type=orm.Int,
            default=lambda: orm.Int(0),
            help=(
                "Absorbing-site index within the structure for this calculation.  "
                "Written into the aggregation config and stored as metadata in "
                "the PathContributionsData HDF5.  Leave at 0 unless running "
                "multi-site ensemble calculations."
            ),
        )
        spec.inputs["metadata"]["options"]["parser_name"].default = "feff.feff"  # type: ignore[index]
        spec.inputs["metadata"]["options"]["withmpi"].default = cls._WITHMPI  # type: ignore[index]

        # --- outputs ----------------------------------------------------------
        spec.output(
            "xas_data",
            valid_type=orm.ArrayData,
            required=False,
            help="Parsed XAS / EXAFS data arrays.",
        )
        spec.output(
            "path_contributions",
            valid_type=PathContributionsData,
            required=False,
            help=(
                "Amplitude-filtered per-path FEFF scattering factors packed "
                "into a single HDF5 file.  Emitted when python_code is "
                "provided and path_cw_threshold >= 0."
            ),
        )
        spec.output(
            "paths_file",
            valid_type=orm.SinglefileData,
            required=False,
            help="paths.dat produced by FEFF (scattering paths).",
        )

        # --- exit codes -------------------------------------------------------
        spec.exit_code(310, "ERROR_MISSING_XMUDA", message="FEFF did not produce xmu.dat.")
        spec.exit_code(
            311,
            "ERROR_POTENTIALS_INCOMPLETE",
            message="Potentials-only run produced no FEFF output; it did not start.",
        )
        spec.exit_code(400, "ERROR_PARSING_FAILED", message="Parser raised an exception: {reason}.")

        # Validate combinations up front: prepare_for_submission cannot report
        # a failure, so anything checkable must be checked here.
        spec.inputs.validator = cls._validate_inputs  # type: ignore[assignment]

    # ------------------------------------------------------------------
    # Input validation
    # ------------------------------------------------------------------

    @staticmethod
    def _validate_inputs(value, _port_namespace) -> str | None:
        """Reject input combinations that cannot produce a valid job.

        Returning a string makes AiiDA raise before the CalcJob node is
        created, which is the only place a CalcJob can refuse its inputs
        cleanly.
        """
        if value is None:
            return None

        has_input_file = "feff_input_file" in value
        has_generated = "structure" in value and "parameters" in value
        if not has_input_file and not has_generated:
            return (
                "Supply either 'feff_input_file', or both 'structure' and 'parameters' "
                "so that feff.inp can be generated."
            )

        threshold = value.get("path_cw_threshold")
        wants_paths = threshold is not None and threshold.value >= 0
        if wants_paths and "python_code" not in value:
            return (
                "'python_code' is required when path_cw_threshold >= 0: the remote "
                "interpreter runs _aggregate_paths.py after FEFF."
            )
        if wants_paths and not has_generated:
            return (
                "Path aggregation needs 'structure' and 'parameters' to record the "
                "absorbing element; it cannot be used with a verbatim feff_input_file."
            )
        return None

    # ------------------------------------------------------------------
    # prepare_for_submission
    # ------------------------------------------------------------------

    def prepare_for_submission(self, folder) -> CalcInfo:
        """Write input files to the *sandbox* folder and return CalcInfo.

        This is the only method plugins must implement.  AiiDA calls it
        before uploading the folder to the remote computer.

        Input combinations are validated by :meth:`_validate_inputs` before the
        node exists; anything wrong here raises rather than returning an exit
        code, which AiiDA cannot accept from this method.
        """
        settings = self.inputs.get("settings", orm.Dict()).get_dict()

        # ----------------------------------------------------------------
        # 1. Build / copy feff.inp
        # ----------------------------------------------------------------
        if "feff_input_file" in self.inputs:
            # User-supplied verbatim input
            src = self.inputs.feff_input_file
            with folder.open(FEFF_INPUT_FILE, "wb") as fh:
                fh.write(src.get_content("rb"))
        else:
            inp_text = self.build_feff_inp(
                self.inputs.structure,
                self.inputs.parameters,
            )
            # FEFF is fixed-format Fortran, so the file is written as bytes
            # with explicit LF endings: a Windows submitter must not be able
            # to leak CRLF into the input.
            with folder.open(FEFF_INPUT_FILE, "wb") as fh:
                fh.write(as_lf_bytes(inp_text))

        # ----------------------------------------------------------------
        # 2. CodeInfo
        # ----------------------------------------------------------------
        codeinfo = CodeInfo()
        codeinfo.code_uuid = self.inputs.code.uuid
        codeinfo.cmdline_params = settings.get("cmdline_params", [])
        codeinfo.stdout_name = FEFF_LOG_FILE
        codeinfo.stderr_name = "stderr.txt"

        # ----------------------------------------------------------------
        # 3. CalcInfo
        # ----------------------------------------------------------------
        calcinfo = CalcInfo()
        calcinfo.codes_info = [codeinfo]
        calcinfo.local_copy_list = []
        calcinfo.remote_copy_list = []

        # When pre-computed potentials are supplied, copy pot.pad and
        # phase.pad from the reference job's remote directory.  All file
        # transfers stay on the HPC — nothing is downloaded.
        if "remote_potentials" in self.inputs:
            remote = self.inputs.remote_potentials
            computer_uuid = remote.computer.uuid
            remote_path = remote.get_remote_path()
            for fname in FEFF_POTENTIAL_FILES:
                calcinfo.remote_copy_list.append((computer_uuid, f"{remote_path}/{fname}", fname))

        retrieve_list: list[str | tuple[str, str, str]] = list(self._DEFAULT_RETRIEVE_LIST)
        retrieve_list.extend(settings.get("additional_retrieve_list", []))
        calcinfo.retrieve_list = retrieve_list

        # When path contributions are requested, write the aggregation script
        # and config to the sandbox, then run them via a second CodeInfo.
        # feff????.dat files are never retrieved — only contributions_raw.h5.
        threshold = self.inputs.path_cw_threshold.value
        if threshold >= 0:
            with folder.open(FEFF_AGGREGATE_SCRIPT, "wb") as fh:
                fh.write(_AGGREGATE_SCRIPT_PATH.read_bytes())
            with folder.open(FEFF_AGGREGATE_CONFIG, "wb") as fh:
                fh.write(
                    as_lf_bytes(
                        json.dumps(
                            {
                                "threshold": float(threshold),
                                "frame_idx": self.inputs.frame_idx.value,
                                "site_idx": self.inputs.site_idx.value,
                                "absorber_element": self._absorber_element(),
                            }
                        )
                    )
                )
            calcinfo.retrieve_list = list(retrieve_list) + [FEFF_CONTRIBUTIONS_RAW]

            agg_codeinfo = CodeInfo()
            agg_codeinfo.code_uuid = self.inputs.python_code.uuid
            agg_codeinfo.cmdline_params = [FEFF_AGGREGATE_SCRIPT]
            agg_codeinfo.withmpi = False
            calcinfo.codes_info = [codeinfo, agg_codeinfo]
            calcinfo.codes_run_mode = datastructures.CodeRunMode.SERIAL

        return calcinfo

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _absorber_element(self) -> str:
        """Return the element symbol of the absorbing atom."""
        return absorber_element(
            self.inputs.structure, self.inputs.parameters.get("absorbing_atom", 0)
        )

    @staticmethod
    def build_feff_inp(
        structure: orm.StructureData,
        parameters: FeffParameters,
    ) -> str:
        """Construct the full text of ``feff.inp`` from AiiDA objects delegating to md_exafs."""
        from md_exafs.feff_input import build_feff_inp as core_build_feff_inp

        cfg = parameters.to_feff_config()
        user_tags = parameters.to_pymatgen_user_tags()
        if "_del" in user_tags:
            cfg.delete_tags = list(user_tags["_del"])

        absorbing_idx = int(parameters.get("absorbing_atom", 0))
        with _spglib_new_error_handling():
            inp_text = core_build_feff_inp(
                structure.get_pymatgen_structure(),
                config=cfg,
                absorber_idx=absorbing_idx,
            )
        return _generator_banner() + f"\n* Absorber site index: {absorbing_idx}\n\n" + inp_text
