"""CLI extensions for aiida-feff (``verdi data feff …``)."""

from __future__ import annotations

import click
from aiida.cmdline.params import arguments
from aiida.cmdline.utils import decorators, echo

from aiida_feff.versions import FEFF_VERSION_ATTR, VERSIONS_ATTR


@click.group("feff")
def cmd_feff():
    """Commands for FeffParameters and XasData nodes."""


# ---------------------------------------------------------------------------
# verdi data feff list
# ---------------------------------------------------------------------------


@cmd_feff.command("list")
@click.option(
    "--type",
    "node_type",
    type=click.Choice(["parameters", "xasdata", "all"], case_sensitive=False),
    default="all",
    show_default=True,
    help="Which data type to list.",
)
@click.option(
    "--limit",
    type=click.IntRange(min=1),
    default=100,
    show_default=True,
    help="Maximum number of nodes to list per type, newest first.",
)
@decorators.with_dbenv()
def cmd_list(node_type, limit):
    """List FeffParameters and/or XasData nodes in the database."""
    from aiida.orm import QueryBuilder

    from aiida_feff.data.parameters import FeffParameters
    from aiida_feff.data.xasdata import XasData

    by_option = {"parameters": ("FeffParameters", FeffParameters), "xasdata": ("XasData", XasData)}
    wanted = list(by_option.values()) if node_type == "all" else [by_option[node_type]]

    rows = []
    for name, cls in wanted:
        qb = QueryBuilder()
        qb.append(cls, project=["id", "uuid", "ctime", "label", "description"])
        # Newest first and bounded: an MD-EXAFS campaign creates these by the
        # tens of thousands, and materialising all of them helps nobody.
        qb.order_by({cls: {"ctime": "desc"}})
        qb.limit(limit)
        for pk, uuid, ctime, label, descr in qb.all():
            rows.append((name, pk, uuid[:8], str(ctime)[:19], label or "", descr or ""))

    if not rows:
        echo.echo("No nodes found.")
        return

    # echo_formatted_list expects objects with named attributes, not rows, so
    # the table is rendered directly.
    from tabulate import tabulate

    echo.echo(tabulate(rows, headers=["Type", "PK", "UUID", "Created", "Label", "Description"]))


# ---------------------------------------------------------------------------
# verdi data feff export
# ---------------------------------------------------------------------------


@cmd_feff.command("export")
@arguments.NODE()
@click.option(
    "--output",
    "-o",
    type=click.Path(),
    default=None,
    help="Write feff.inp to this path (default: print to stdout).",
)
@decorators.with_dbenv()
def cmd_export(node, output):
    """Export a FeffParameters node as a feff.inp preview.

    NODE can be a PK, UUID, or label.
    """
    from aiida_feff.data.parameters import FeffParameters

    if not isinstance(node, FeffParameters):
        echo.echo_critical(f"Node {node.pk} is not a FeffParameters node.")

    cards = node.to_feff_cards()
    text = "\n".join(["* Preview generated by aiida-feff", ""] + cards + [""])

    if output:
        with open(output, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        echo.echo_success(f"Written to {output}")
    else:
        echo.echo(text)


# ---------------------------------------------------------------------------
# verdi data feff show
# ---------------------------------------------------------------------------


@cmd_feff.command("show")
@arguments.NODE()
@decorators.with_dbenv()
def cmd_show(node):
    """Show the arrays stored in an XasData node."""
    from aiida_feff.data.xasdata import XasData

    if not isinstance(node, XasData):
        echo.echo_critical(f"Node {node.pk} is not an XasData node.")

    echo.echo(f"XasData PK={node.pk}  label='{node.label}'")
    for name in node.get_arraynames():
        arr = node.get_array(name)
        echo.echo(f"  {name:<14s}  shape={arr.shape}  dtype={arr.dtype}")

    for key in (FEFF_VERSION_ATTR, VERSIONS_ATTR, "chi_source", "fourier_params"):
        value = node.base.attributes.get(key, None)
        if value is not None:
            echo.echo(f"  {key:<14s}  {value}")
